### ISSUE TITLE
no root 原理－签名

### ISSUE THREAD

**Issue by wuming2** [blackbbc/Evil-Hide#5]
查看了源码，所以在原生系统下可使用是因为使用了platform签名…… 通过android:sharedUserId="android.uid.system"获取了系统权限
建议在原理非root中说明

感谢源码分享

**Comment by wuming2** [comment]
nexus 5x不可用，虚拟机nexus 5可用

**Comment by AldenLei** [comment]
请问这个程序系统签名是怎么做的呢？
